name: Dynatrace Health, Deployment & CPU Demo

on:
  push:
    branches: [ main ]
  workflow_dispatch:
    inputs:
      scenario:
        description: "Choose scenario to simulate"
        required: true
        default: "healthy"
        type: choice
        options:
          - healthy
          - cpu_unhealthy
          - deploy_fail

jobs:
  demo:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      # ✅ Healthy Run
      - name: Healthy job
        if: ${{ github.event_name == 'push' || github.event.inputs.scenario == 'healthy' }}
        run: echo "✅ Healthy run success"

      - name: Send Healthy Event
        if: ${{ github.event_name == 'push' || github.event.inputs.scenario == 'healthy' }}
        run: |
          curl -X POST "$https://jvc12148.live.dynatrace.com/api/v2/events/ingest" \
            -H "Authorization: Api-Token ${{ secrets.DT_API_TOKEN }}" \
            -H "Content-Type: application/json" \
            -d '{"eventType":"CUSTOM_INFO","title":"Healthy Build","description":"GitHub Action succeeded"}'

      # ⚠️ CPU Stress
      - name: CPU Stress Simulation
        if: ${{ github.event.inputs.scenario == 'cpu_unhealthy' }}
        run: |
          echo "⚠️ Simulating CPU stress..."
          python3 - <<'PY'
          import time
          start=time.time()
          while time.time()-start<10: pass
          PY

      - name: Send CPU Alert
        if: ${{ github.event.inputs.scenario == 'cpu_unhealthy' }}
        run: |
          curl -X POST "$https://jvc12148.live.dynatrace.com/api/v2/events/ingest" \
            -H "Authorization: Api-Token ${{ secrets.DT_API_TOKEN }}" \
            -H "Content-Type: application/json" \
            -d '{"eventType":"CUSTOM_ALERT","title":"High CPU Alert","description":"Dummy CPU load from GitHub Action"}'

      # ❌ Deployment Failure
      - name: Fake Deployment
        if: ${{ github.event.inputs.scenario == 'deploy_fail' }}
        run: exit 1
        continue-on-error: true

      - name: Send Deployment Failure
        if: ${{ github.event.inputs.scenario == 'deploy_fail' }}
        run: |
          curl -X POST "$https://jvc12148.live.dynatrace.com/api/v2/events/ingest" \
            -H "Authorization: Api-Token ${{ secrets.DT_API_TOKEN }}" \
            -H "Content-Type: application/json" \
            -d '{"eventType":"CUSTOM_ALERT","title":"Deployment Failure","description":"Simulated deployment failed in GitHub Action"}'
