name: Dynatrace Dummy Alert

on:
  workflow_dispatch:   # run manually from Actions tab

jobs:
  send-alert:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: Send Dummy Dynatrace Alert
        run: Test.py
        env:
          DT_API_TOKEN: ${{ secrets.DT_API_TOKEN }}
          DT_ENV_URL: ${{ secrets.DT_URL }}
