name: CPU Stress Test

on:
  workflow_dispatch:   # Manual trigger from GitHub UI
  schedule:
    - cron: "0 */6 * * *"   # Optional: run every 6 hours

jobs:
  cpu-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: Run CPU Stress Script
        run: python Test.py
