name: Dummy ALB Health Test

on:
  push:
    branches: [ main ]

jobs:
  health-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install Flask requests

      - name: Run Dummy App in background
        run: |
          nohup python app.py &
          sleep 5

      - name: Check Health
        run: |
          python - <<EOF
          import requests
          r = requests.get("http://127.0.0.1:5000/health")
          print(r.status_code, r.json())
          if r.status_code != 200:
              raise Exception("Dummy ALB Target Unhealthy!")
          EOF
